id: 092b5c5db35b4dc2b4b093b2a98a5256
initial_creation_type: ocr
source_metadata:
  volumes:
    db68876da80e4933851efda8cd5578c3:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: རྣལ་འབྱོར་ལམ་གྱི་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 26
